---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-oofoghlu-v1-fuzzycronjob
  failurePolicy: Fail
  name: vfuzzycronjob.kb.io
  rules:
  - apiGroups:
    - batch.oofoghlu
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fuzzycronjobs
  sideEffects: None
