# permissions for end users to edit fuzzycronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fuzzycronjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fuzzycron
    app.kubernetes.io/part-of: fuzzycron
    app.kubernetes.io/managed-by: kustomize
  name: fuzzycronjob-editor-role
rules:
- apiGroups:
  - batch.oofoghlu
  resources:
  - fuzzycronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.oofoghlu
  resources:
  - fuzzycronjobs/status
  verbs:
  - get
