---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.oofoghlu
  resources:
  - fuzzycronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.oofoghlu
  resources:
  - fuzzycronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.oofoghlu
  resources:
  - fuzzycronjobs/status
  verbs:
  - get
  - patch
  - update
