apiVersion: batch.oofoghlu/v1
kind: FuzzyCronJob
metadata:
  labels:
    app.kubernetes.io/name: fuzzycronjob
    app.kubernetes.io/instance: fuzzycronjob-sample
    app.kubernetes.io/part-of: fuzzycron
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fuzzycron
  name: fuzzycronjob-sample
spec:
  # TODO(user): Add fields here
  schedule: "H H * * *"
  cronJob:
    startingDeadlineSeconds: 60
    concurrencyPolicy: Allow # explicitly specify, but Allow is also default.
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: hello
              image: busybox
              args:
              - /bin/sh
              - -c
              - date; echo Hello from the Kubernetes cluster
            restartPolicy: OnFailure
